version: "3"
services:
  server:
    container_name: server
    restart: unless-stopped
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    env_file: ./server/.env
    ports: 
      - 4000:4000
    networks:
      - app-network
    depends_on: 
      - db
  db:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    volumes:
      - ./server/data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data: